import { PrismaClient, Role, ApprovalStatus, WorkflowStatus, Severity } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Users
  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: 'admin@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'Sarah Chen',
        email: 'admin@stateconstruction.com',
        role: Role.ADMIN,
        department: 'IT',
        active: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'jmartin@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'James Martin',
        email: 'jmartin@stateconstruction.com',
        role: Role.PM,
        department: 'Project Team',
        active: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'lthompson@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'Lisa Thompson',
        email: 'lthompson@stateconstruction.com',
        role: Role.PMO,
        department: 'Project Team',
        active: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'mrodriguez@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'Marco Rodriguez',
        email: 'mrodriguez@stateconstruction.com',
        role: Role.DEPARTMENT_APPROVER,
        department: 'Field Team',
        active: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'pnguyen@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'Patricia Nguyen',
        email: 'pnguyen@stateconstruction.com',
        role: Role.EXECUTIVE_READONLY,
        department: 'Executive',
        active: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'dkumar@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'Dev Kumar',
        email: 'dkumar@stateconstruction.com',
        role: Role.STANDARD_CONTRIBUTOR,
        department: 'Drafting/Engineer',
        active: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'awilson@stateconstruction.com' },
      update: {},
      create: {
        displayName: 'Angela Wilson',
        email: 'awilson@stateconstruction.com',
        role: Role.DEPARTMENT_APPROVER,
        department: 'Purchasing',
        active: true,
      },
    }),
  ]);

  const [admin, pm, pmo, deptApprover, executive, contributor, purchasingApprover] = users;

  // Config thresholds
  await Promise.all([
    prisma.configThreshold.upsert({
      where: { key: 'vendor_delay_threshold_days' },
      update: {},
      create: { key: 'vendor_delay_threshold_days', value: '14', description: 'Days before vendor delay is flagged as major' },
    }),
    prisma.configThreshold.upsert({
      where: { key: 'cost_variance_threshold' },
      update: {},
      create: { key: 'cost_variance_threshold', value: '25000', description: 'Cost variance ($) threshold for watchout' },
    }),
    prisma.configThreshold.upsert({
      where: { key: 'open_days_warning' },
      update: {},
      create: { key: 'open_days_warning', value: '30', description: 'Days open before warning' },
    }),
    prisma.configThreshold.upsert({
      where: { key: 'open_days_critical' },
      update: {},
      create: { key: 'open_days_critical', value: '60', description: 'Days open before critical alert' },
    }),
  ]);

  // Lessons
  const lessonsData = [
    {
      lessonId: 'LL-2024-101-001',
      workflowStatus: WorkflowStatus.APPROVED_REUSABLE,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.APPROVED,
      departmentApproval: ApprovalStatus.APPROVED,
      finalReusableApproval: ApprovalStatus.APPROVED,
      pmApprovalDate: new Date('2024-03-15'),
      pmoApprovalDate: new Date('2024-03-18'),
      departmentApprovalDate: new Date('2024-03-20'),
      finalApprovalDate: new Date('2024-03-20'),
      pmApprovalBy: pm.id,
      pmoApprovalBy: pmo.id,
      departmentApprovalBy: deptApprover.id,
      projectNumber: '2024-101',
      projectName: 'Highline Tower Curtain Wall',
      client: 'Brookfield Properties',
      location: 'Toronto, ON',
      projectType: 'Commercial High-Rise',
      system: 'Curtain Wall',
      phase: 'Installation',
      category: 'Quality',
      severity: Severity.HIGH,
      description: 'Sealant adhesion failure on floors 22-28 due to substrate contamination from concrete dust. Required re-application of 340 linear meters of structural sealant.',
      rootCause: 'Concrete grinding on adjacent floors was performed without adequate protection of installed curtain wall frames. No cleaning protocol was enforced before sealant application.',
      lessonLearned: 'Implement mandatory substrate inspection and cleaning checklist before any sealant application. Coordinate with GC to schedule grinding operations with buffer zones.',
      preventiveAction: 'Add pre-sealant substrate inspection hold point to QC checklist. Require sign-off from glazing foreman and GC site super before sealant crew mobilizes.',
      costImpact: 45000,
      costAvoided: 0,
      scheduleImpact: 12,
      vendorRelated: false,
      vendorName: null,
      claimsRelevant: true,
      evidenceLink: 'https://sharepoint.stateconstruction.com/projects/2024-101/photos/sealant-failure',
      minutesLink: 'https://sharepoint.stateconstruction.com/projects/2024-101/minutes/2024-03-10',
      createdByUserId: pm.id,
      createdByDepartment: 'Project Team',
      primaryResponsibleDepartment: 'Field Team',
      dateIdentified: new Date('2024-03-08'),
      targetDate: new Date('2024-04-15'),
      dateClosed: new Date('2024-03-20'),
    },
    {
      lessonId: 'LL-2024-101-002',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      pmApprovalDate: new Date('2024-06-20'),
      pmApprovalBy: pm.id,
      projectNumber: '2024-101',
      projectName: 'Highline Tower Curtain Wall',
      client: 'Brookfield Properties',
      location: 'Toronto, ON',
      projectType: 'Commercial High-Rise',
      system: 'Curtain Wall',
      phase: 'Engineering',
      category: 'Design',
      severity: Severity.MEDIUM,
      description: 'Thermal break detail at spandrel-to-vision transition was under-specified in shop drawings, leading to condensation issues at mock-up stage.',
      rootCause: 'Shop drawing review did not include building science review for thermal performance at transition details.',
      lessonLearned: 'All spandrel-to-vision transitions must be reviewed by Building Science team during shop drawing phase.',
      preventiveAction: 'Add Building Science review gate to shop drawing workflow for all curtain wall projects.',
      costImpact: 8500,
      costAvoided: 120000,
      scheduleImpact: 5,
      vendorRelated: false,
      claimsRelevant: false,
      createdByUserId: contributor.id,
      createdByDepartment: 'Drafting/Engineer',
      primaryResponsibleDepartment: 'Drafting/Engineer',
      dateIdentified: new Date('2024-06-15'),
      targetDate: new Date('2024-07-30'),
    },
    {
      lessonId: 'LL-2024-205-001',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.PENDING,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      projectNumber: '2024-205',
      projectName: 'Lakeside Medical Center',
      client: 'Trillium Health Partners',
      location: 'Mississauga, ON',
      projectType: 'Institutional',
      system: 'Window Wall',
      phase: 'Procurement',
      category: 'Vendor Management',
      severity: Severity.CRITICAL,
      description: 'Primary glass supplier (VistaClear) delivered IGU units 6 weeks late with 15% rejection rate due to seal failures. Caused cascading schedule delays across 3 floors.',
      rootCause: 'Vendor capacity was overcommitted. No secondary source was qualified. Incoming QC inspection was not rigorous enough to catch early seal defects.',
      lessonLearned: 'Qualify dual-source suppliers for all critical glass components. Implement incoming inspection protocol with statistical sampling.',
      preventiveAction: 'Purchasing to maintain approved vendor list with minimum 2 qualified suppliers per critical component. Add incoming QC hold point for IGU deliveries.',
      costImpact: 185000,
      costAvoided: 0,
      scheduleImpact: 42,
      vendorRelated: true,
      vendorName: 'VistaClear Glass Inc.',
      claimsRelevant: true,
      evidenceLink: 'https://sharepoint.stateconstruction.com/projects/2024-205/NCR/vcg-001',
      createdByUserId: purchasingApprover.id,
      createdByDepartment: 'Purchasing',
      primaryResponsibleDepartment: 'Purchasing',
      dateIdentified: new Date('2024-08-01'),
      targetDate: new Date('2024-09-15'),
    },
    {
      lessonId: 'LL-2024-205-002',
      workflowStatus: WorkflowStatus.APPROVED_REUSABLE,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.APPROVED,
      departmentApproval: ApprovalStatus.APPROVED,
      finalReusableApproval: ApprovalStatus.APPROVED,
      pmApprovalDate: new Date('2024-05-10'),
      pmoApprovalDate: new Date('2024-05-12'),
      departmentApprovalDate: new Date('2024-05-14'),
      finalApprovalDate: new Date('2024-05-14'),
      pmApprovalBy: pm.id,
      pmoApprovalBy: pmo.id,
      departmentApprovalBy: deptApprover.id,
      projectNumber: '2024-205',
      projectName: 'Lakeside Medical Center',
      client: 'Trillium Health Partners',
      location: 'Mississauga, ON',
      projectType: 'Institutional',
      system: 'Storefront',
      phase: 'Shop Drawing',
      category: 'Process Improvement',
      severity: Severity.LOW,
      description: 'Implemented 3D coordination model for storefront-to-mechanical interface. Eliminated 90% of field conflicts compared to previous project.',
      rootCause: 'Previous projects relied on 2D overlay for coordination which missed vertical conflicts at mechanical penetrations.',
      lessonLearned: '3D BIM coordination for storefront interfaces significantly reduces field rework. ROI is positive even for mid-size projects.',
      preventiveAction: 'Standardize 3D coordination model requirement for all storefront and curtain wall projects above $500K.',
      costImpact: 0,
      costAvoided: 75000,
      scheduleImpact: -8,
      vendorRelated: false,
      claimsRelevant: false,
      createdByUserId: contributor.id,
      createdByDepartment: 'Drafting/Engineer',
      primaryResponsibleDepartment: 'Drafting/Engineer',
      dateIdentified: new Date('2024-04-20'),
      targetDate: new Date('2024-06-01'),
      dateClosed: new Date('2024-05-14'),
    },
    {
      lessonId: 'LL-2024-310-001',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.PENDING,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      projectNumber: '2024-310',
      projectName: 'Aurora Office Complex',
      client: 'Oxford Properties',
      location: 'Aurora, ON',
      projectType: 'Commercial Low-Rise',
      system: 'Entrance Systems',
      phase: 'Installation',
      category: 'Safety',
      severity: Severity.CRITICAL,
      description: 'Revolving door motor unit arrived damaged. Installer proceeded without reporting damage, resulting in intermittent motor failure and door entrapment incident (no injury).',
      rootCause: 'No formal receiving inspection for door hardware. Installer did not follow damaged goods reporting procedure.',
      lessonLearned: 'All motorized entrance systems must undergo receiving inspection with documented sign-off before installation begins.',
      preventiveAction: 'Create entrance systems receiving checklist. Mandate stop-work if damage is found on motorized components.',
      costImpact: 32000,
      costAvoided: 0,
      scheduleImpact: 18,
      vendorRelated: true,
      vendorName: 'DoorTech Systems',
      claimsRelevant: true,
      evidenceLink: 'https://sharepoint.stateconstruction.com/projects/2024-310/safety/incident-001',
      minutesLink: 'https://sharepoint.stateconstruction.com/projects/2024-310/minutes/2024-07-15',
      createdByUserId: deptApprover.id,
      createdByDepartment: 'Field Team',
      primaryResponsibleDepartment: 'Shipping/Receiving',
      dateIdentified: new Date('2024-07-10'),
      targetDate: new Date('2024-08-30'),
    },
    {
      lessonId: 'LL-2024-310-002',
      workflowStatus: WorkflowStatus.APPROVED_REUSABLE,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.APPROVED,
      departmentApproval: ApprovalStatus.APPROVED,
      finalReusableApproval: ApprovalStatus.APPROVED,
      pmApprovalDate: new Date('2024-04-05'),
      pmoApprovalDate: new Date('2024-04-08'),
      departmentApprovalDate: new Date('2024-04-10'),
      finalApprovalDate: new Date('2024-04-10'),
      pmApprovalBy: pm.id,
      pmoApprovalBy: pmo.id,
      departmentApprovalBy: purchasingApprover.id,
      projectNumber: '2024-310',
      projectName: 'Aurora Office Complex',
      client: 'Oxford Properties',
      location: 'Aurora, ON',
      projectType: 'Commercial Low-Rise',
      system: 'Aluminum Framing',
      phase: 'Production',
      category: 'Process Improvement',
      severity: Severity.MEDIUM,
      description: 'Switched to pre-assembled corner keys for aluminum framing. Reduced production assembly time by 22% and eliminated field rework on corner joints.',
      rootCause: 'Previous method of field-assembled corner keys was error-prone and time-consuming.',
      lessonLearned: 'Pre-assembled corner keys improve both production throughput and field quality. Should be standard for all aluminum framing projects.',
      preventiveAction: 'Update production SOPs to default to pre-assembled corner keys. Update estimating templates with revised labor factors.',
      costImpact: 0,
      costAvoided: 28000,
      scheduleImpact: -5,
      vendorRelated: false,
      claimsRelevant: false,
      createdByUserId: pm.id,
      createdByDepartment: 'Project Team',
      primaryResponsibleDepartment: 'Production',
      dateIdentified: new Date('2024-03-20'),
      targetDate: new Date('2024-05-01'),
      dateClosed: new Date('2024-04-10'),
    },
    {
      lessonId: 'LL-2025-401-001',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.APPROVED,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      pmApprovalDate: new Date('2025-02-10'),
      pmoApprovalDate: new Date('2025-02-14'),
      pmApprovalBy: pm.id,
      pmoApprovalBy: pmo.id,
      projectNumber: '2025-401',
      projectName: 'Waterfront Condo Phase 2',
      client: 'Tridel Corp',
      location: 'Toronto, ON',
      projectType: 'Residential High-Rise',
      system: 'Curtain Wall',
      phase: 'Installation',
      category: 'Coordination',
      severity: Severity.HIGH,
      description: 'Fire-stop installation by others interfered with curtain wall anchor adjustment. 14 anchors required re-setting after fire-stop crew modified anchor brackets without notification.',
      rootCause: 'No coordination protocol between glazing and fire-stopping trades. GC did not enforce sequencing.',
      lessonLearned: 'Curtain wall anchor adjustment period must be protected in schedule. Fire-stop work must not commence until anchor sign-off is complete.',
      preventiveAction: 'Add anchor protection clause to GC coordination meetings. Require written sign-off before adjacent trades access curtain wall anchors.',
      costImpact: 22000,
      costAvoided: 0,
      scheduleImpact: 8,
      vendorRelated: false,
      claimsRelevant: true,
      evidenceLink: 'https://sharepoint.stateconstruction.com/projects/2025-401/RFI/anchor-reset',
      createdByUserId: deptApprover.id,
      createdByDepartment: 'Field Team',
      primaryResponsibleDepartment: 'Field Team',
      dateIdentified: new Date('2025-02-01'),
      targetDate: new Date('2025-03-15'),
    },
    {
      lessonId: 'LL-2025-401-002',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.PENDING,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      projectNumber: '2025-401',
      projectName: 'Waterfront Condo Phase 2',
      client: 'Tridel Corp',
      location: 'Toronto, ON',
      projectType: 'Residential High-Rise',
      system: 'Window Wall',
      phase: 'Engineering',
      category: 'Design',
      severity: Severity.MEDIUM,
      description: 'Wind load calculations did not account for updated building code corner zone factors. Required engineering revision after permit review.',
      rootCause: 'Engineering team was using previous code edition factors. No code update notification process existed.',
      lessonLearned: 'Maintain a code change log and distribute updates to engineering team quarterly. Verify code edition at project kickoff.',
      preventiveAction: 'Assign R&D lead to track building code amendments. Add code edition verification to engineering kickoff checklist.',
      costImpact: 12000,
      costAvoided: 0,
      scheduleImpact: 15,
      vendorRelated: false,
      claimsRelevant: false,
      createdByUserId: contributor.id,
      createdByDepartment: 'Drafting/Engineer',
      primaryResponsibleDepartment: 'R&D',
      dateIdentified: new Date('2025-01-20'),
      targetDate: new Date('2025-03-01'),
    },
    {
      lessonId: 'LL-2025-505-001',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.PENDING,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      projectNumber: '2025-505',
      projectName: 'Provincial Courthouse Retrofit',
      client: 'Infrastructure Ontario',
      location: 'Ottawa, ON',
      projectType: 'Institutional',
      system: 'Curtain Wall',
      phase: 'Breakdown',
      category: 'Estimating',
      severity: Severity.HIGH,
      description: 'Breakdown missed 240 LF of head flashing at parapet condition. Discovery during production caused material re-order and 3-week delay.',
      rootCause: 'Architectural details at parapet were ambiguous. Breakdown team did not issue RFI to clarify scope before finalizing material list.',
      lessonLearned: 'All parapet and roof-to-wall transition details must be verified with architect via RFI during breakdown phase.',
      preventiveAction: 'Add parapet/roof transition verification to breakdown checklist. Flag ambiguous details for mandatory RFI.',
      costImpact: 38000,
      costAvoided: 0,
      scheduleImpact: 21,
      vendorRelated: true,
      vendorName: 'MetalCraft Flashings Ltd.',
      claimsRelevant: false,
      evidenceLink: 'https://sharepoint.stateconstruction.com/projects/2025-505/RFI/parapet-001',
      createdByUserId: pm.id,
      createdByDepartment: 'Project Team',
      primaryResponsibleDepartment: 'Breakdown',
      dateIdentified: new Date('2025-03-10'),
      targetDate: new Date('2025-04-30'),
    },
    {
      lessonId: 'LL-2025-505-002',
      workflowStatus: WorkflowStatus.APPROVED_REUSABLE,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.APPROVED,
      departmentApproval: ApprovalStatus.APPROVED,
      finalReusableApproval: ApprovalStatus.APPROVED,
      pmApprovalDate: new Date('2025-01-20'),
      pmoApprovalDate: new Date('2025-01-22'),
      departmentApprovalDate: new Date('2025-01-25'),
      finalApprovalDate: new Date('2025-01-25'),
      pmApprovalBy: pm.id,
      pmoApprovalBy: pmo.id,
      departmentApprovalBy: deptApprover.id,
      projectNumber: '2025-505',
      projectName: 'Provincial Courthouse Retrofit',
      client: 'Infrastructure Ontario',
      location: 'Ottawa, ON',
      projectType: 'Institutional',
      system: 'Storefront',
      phase: 'Servicing',
      category: 'Warranty',
      severity: Severity.LOW,
      description: 'Proactive warranty inspection program on completed storefront identified minor gasket shrinkage at 8 locations before client complaint. Repaired under warranty at minimal cost.',
      rootCause: 'Gasket material from specific lot had higher shrinkage rate than spec. Early detection prevented larger failure.',
      lessonLearned: 'Proactive 6-month and 12-month warranty inspections catch issues before they become complaints. Program should be standard.',
      preventiveAction: 'Implement standard post-completion inspection program at 6 and 12 months for all storefront and curtain wall projects.',
      costImpact: 2200,
      costAvoided: 45000,
      scheduleImpact: 0,
      vendorRelated: false,
      claimsRelevant: false,
      createdByUserId: pm.id,
      createdByDepartment: 'Project Team',
      primaryResponsibleDepartment: 'Servicing',
      dateIdentified: new Date('2025-01-10'),
      targetDate: new Date('2025-02-28'),
      dateClosed: new Date('2025-01-25'),
    },
    {
      lessonId: 'LL-2025-602-001',
      workflowStatus: WorkflowStatus.SUBMITTED,
      pmApproval: ApprovalStatus.PENDING,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.PENDING,
      finalReusableApproval: ApprovalStatus.PENDING,
      projectNumber: '2025-602',
      projectName: 'King West Mixed Use Tower',
      client: 'Great Gulf Homes',
      location: 'Toronto, ON',
      projectType: 'Mixed Use',
      system: 'Curtain Wall',
      phase: 'Installation',
      category: 'Logistics',
      severity: Severity.MEDIUM,
      description: 'Material staging area was reassigned by GC without notice, requiring emergency crane time to relocate 40 curtain wall panels. Panels stored improperly during relocation.',
      rootCause: 'No formal staging area agreement in subcontract. GC site logistics plan did not protect glazing storage zones.',
      lessonLearned: 'Staging area requirements and protection must be formalized in subcontract terms. Include penalty clause for unauthorized relocation.',
      preventiveAction: 'Add staging area protection clause to standard subcontract template. PM to verify staging in pre-mobilization checklist.',
      costImpact: 15000,
      costAvoided: 0,
      scheduleImpact: 4,
      vendorRelated: false,
      claimsRelevant: true,
      minutesLink: 'https://sharepoint.stateconstruction.com/projects/2025-602/minutes/2025-03-20',
      createdByUserId: deptApprover.id,
      createdByDepartment: 'Field Team',
      primaryResponsibleDepartment: 'Field Team',
      dateIdentified: new Date('2025-03-18'),
      targetDate: new Date('2025-05-01'),
    },
    {
      lessonId: 'LL-2025-602-002',
      workflowStatus: WorkflowStatus.IN_REVIEW,
      pmApproval: ApprovalStatus.APPROVED,
      pmoApproval: ApprovalStatus.PENDING,
      departmentApproval: ApprovalStatus.APPROVED,
      finalReusableApproval: ApprovalStatus.PENDING,
      pmApprovalDate: new Date('2025-03-28'),
      departmentApprovalDate: new Date('2025-03-30'),
      pmApprovalBy: pm.id,
      departmentApprovalBy: purchasingApprover.id,
      projectNumber: '2025-602',
      projectName: 'King West Mixed Use Tower',
      client: 'Great Gulf Homes',
      location: 'Toronto, ON',
      projectType: 'Mixed Use',
      system: 'Aluminum Framing',
      phase: 'Procurement',
      category: 'Vendor Management',
      severity: Severity.HIGH,
      description: 'Extrusion supplier substituted alloy grade without notification. Discovered during anodizing when color match failed. 2,400 LF of extrusion rejected.',
      rootCause: 'Purchase order did not specify alloy grade explicitly. Vendor substitution policy was not enforced.',
      lessonLearned: 'All extrusion POs must specify alloy grade, temper, and finish requirements explicitly. Require material test certificates with each shipment.',
      preventiveAction: 'Update PO template for aluminum extrusions to include mandatory alloy/temper spec. Add MTR verification to receiving inspection.',
      costImpact: 67000,
      costAvoided: 0,
      scheduleImpact: 28,
      vendorRelated: true,
      vendorName: 'AlumaPro Extrusions',
      claimsRelevant: true,
      evidenceLink: 'https://sharepoint.stateconstruction.com/projects/2025-602/NCR/aluma-001',
      createdByUserId: purchasingApprover.id,
      createdByDepartment: 'Purchasing',
      primaryResponsibleDepartment: 'Purchasing',
      dateIdentified: new Date('2025-03-25'),
      targetDate: new Date('2025-05-15'),
    },
  ];

  for (const data of lessonsData) {
    await prisma.lesson.upsert({
      where: { lessonId: data.lessonId },
      update: {},
      create: data,
    });
  }

  // Create audit entries for approved lessons
  const approvedLessons = await prisma.lesson.findMany({
    where: { pmApproval: ApprovalStatus.APPROVED },
  });

  for (const lesson of approvedLessons) {
    const existingAudit = await prisma.approvalAudit.findFirst({
      where: { lessonId: lesson.id, actionType: 'LESSON_CREATED' },
    });
    if (!existingAudit) {
      await prisma.approvalAudit.create({
        data: {
          lessonId: lesson.id,
          actionType: 'LESSON_CREATED',
          oldValue: null,
          newValue: 'SUBMITTED',
          changedByUserId: lesson.createdByUserId,
          changedByRole: 'CREATOR',
          changedAt: lesson.createdAt,
        },
      });
    }
  }

  console.log('Seed completed successfully.');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
